apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sit-project
  namespace: argocd
spec:
  description: "SIT microservices"
  sourceRepos:
    - https://gitlab.com/nanuchi/argocd-app-config.git
  destinations:

---


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: sit-project                # reference the AppProject
  source:
    repoURL: https://gitlab.com/nanuchi/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sit
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp1
  namespace: argocd
spec:
  project: sit-project                # reference the AppProject
  source:
    repoURL: https://gitlab.com/nanuchi/argocd-app-config.git
    targetRevision: HEAD
    path: dev1
  destination:
    server: https://kubernetes.default.svc
    namespace: sit
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
