apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blue-green-demo
  namespace: argocd
spec:
  description: Blue-green demo project
  sourceRepos:
  - "*"
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc

